doctrine:
  orm:
    mappings:
      TrainCourseBundle:
        type: attribute
        dir: '%kernel.project_dir%/vendor/tourze/train-course-bundle/src/Entity'
        prefix: 'Tourze\TrainCourseBundle\Entity'
        alias: TrainCourse
        is_bundle: false
    
    # 实体管理器配置
    entity_managers:
      default:
        mappings:
          TrainCourseBundle:
            type: attribute
            dir: '%kernel.project_dir%/vendor/tourze/train-course-bundle/src/Entity'
            prefix: 'Tourze\TrainCourseBundle\Entity'
            alias: TrainCourse

  dbal:
    # 数据库表前缀配置
    schema_filter: ~
    
    # 类型映射
    types:
      uuid: Symfony\Bridge\Doctrine\Types\UuidType
      json: Doctrine\DBAL\Types\JsonType 